apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-backup
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          initContainers:
            - name: tar 
              image: alpine 
              volumeMounts:
                - name: backup 
                  mountPath: /backup
                - name: data
                  mountPath: /data
              command: ["/bin/sh", "-c"]
              args:
                - tar -zcvf /backup/home.tar /data 
              securityContext:
                runAsUser: 0
                runAsGroup: 1000
            - name: encrypt 
              image: mozilla/sops:v3.7.3-alpine 
              volumeMounts:
                - name: backup 
                  mountPath: /backup
              command: ["/bin/sh", "-c"]
              args: 
                - sops --verbose --encrypt --age age1yzj8tdyqfz0c484jdfzs82g862d6e935txu2wz4w58ycsvcwqvxq2crzld /backup/home.tar > /backup/home.tar.enc;
                  rm /backup/home.tar
              securityContext:
                runAsUser: 0
                runAsGroup: 1000
          containers:
            - name: push 
              image: google/cloud-sdk:405.0.0-alpine 
              volumeMounts:
                - name: backup 
                  mountPath: /backup
                - mountPath: /.secrets/gcp/gcpServiceUser.json
                  name: gcpserviceuser
                  subPath: gcpServiceUser.json
              command: ["/bin/sh", "-c"]
              args:
                - gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS};
                  gsutil -h Content-Type:application/octet-stream cp -v /backup/home.tar.enc gs://32424361-154a-4ebd-843d-6763887ccfc4/home.tar.enc;
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /.secrets/gcp/gcpServiceUser.json
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
          restartPolicy: Never
          volumes:
            - name: backup 
              emptyDir: {}
            - name: gcpserviceuser
              secret:
                secretName: gcpserviceuser.json
            - name: data
              hostPath:
                path: /ssd/k3s/home
                type: Directory

